In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import csv

# 读取

In [2]:
xlsx = 'C:/Users/LuoZN/Desktop/客流数据/【客流+车场数据】0813.xlsx'

In [3]:
'/'.join(xlsx.split('/')[:-2])+'/heat.jpg'

'C:/Users/LuoZN/Desktop/heat.jpg'

### 出入口及通道日客流数

In [4]:
traffic_pathway_day = pd.read_excel(xlsx,'出入口及通道日客流数')
traffic_pathway_day.head(3)

,日期,广场级,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
0,NaT,10号门,1AF1/2/3号客梯厅旁通道,1AF-11号通道,1AF-1号消防电梯厅,1AF-2号通道,1AF-3号通道,1AF-4号通道,1AF5号消防电梯厅,1AF6/7/8号客梯厅旁通道,...,UNIQLO外围通道,VERO MODA外围通道,宝贝王外围通道,宝贝王早教外围通道,大玩家外围通道,汉邦剪裁外围通道,苏宁外围通道,西面1AF至1BF楼梯通道,橡皮筋外围通道,星巴克外围通道
1,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-12-01,5338,107,3029,0,5567,5,2384,41,65,...,170,1,1496,26,6222,7,1133,348,8,1010

In [5]:
name_pathway = list(traffic_pathway_day.iloc[0])[1:]
name_pathway[:10]

['10号门',
 '1AF1/2/3号客梯厅旁通道',
 '1AF-11号通道',
 '1AF-1号消防电梯厅',
 '1AF-2号通道',
 '1AF-3号通道',
 '1AF-4号通道',
 '1AF5号消防电梯厅',
 '1AF6/7/8号客梯厅旁通道',
 '1AF-6号通道']

In [6]:
traffic_pathway_day = traffic_pathway_day[2:]
traffic_pathway_day['日期'] = pd.to_datetime(traffic_pathway_day['日期'])
traffic_pathway_day = traffic_pathway_day.set_index('日期',drop = True)
traffic_pathway_day.columns = [['广场级' for i in name_pathway],name_pathway]
traffic_pathway_day.head()

             广场级                                                          \
            10号门 1AF1/2/3号客梯厅旁通道 1AF-11号通道 1AF-1号消防电梯厅 1AF-2号通道 1AF-3号通道
日期
2018-12-01  5338             107      3029           0     5567        5
2018-12-02  3660             146      2442           6     5410       58
2018-12-03  1625              15       644           8     1917       12
2018-12-04  1507              16       506           1     1771       47
2018-12-05  1097              42       499           4     1717       16

                                                          ...               \
           1AF-4号通道 1AF5号消防电梯厅 1AF6/7/8号客梯厅旁通道 1AF-6号通道   ...   UNIQLO外围通道
日期                                                        ...
2018-12-01     2384         41              65       42   ...          170
2018-12-02     2100         30               9       50   ...          172
2018-12-03      283         20               3        4   ...          128
2018-12-04      301         19               3       74   ...          148
2018-12-05      216          9               0       54   ...          162

                                                                    \
           VERO MODA外围通道 宝贝王外围通道 宝贝王早教外围通道 大玩家外围通道 汉邦剪裁外围通道 苏宁外围通道
日期
2018-12-01             1    1496        26    6222        7   1133
2018-12-02             0    1510        40    5713        2    773
2018-12-03             0     437        18    1398       18    338
2018-12-04             1     272        21    1734       11    298
2018-12-05             0     283        26    1439        7    264


           西面1AF至1BF楼梯通道 橡皮筋外围通道 星巴克外围通道
日期
2018-12-01           348       8    1010
2018-12-02           211       3     754
2018-12-03           118       1     378
2018-12-04           125       1     234
2018-12-05           110       1     242

[5 rows x 66 columns]

### 店铺日客流量

In [7]:
traffic_store_day= pd.read_excel(xlsx,'店铺日客流量')
traffic_store_day.head(3)

,日期,店铺级,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 273,Unnamed: 274,Unnamed: 275,Unnamed: 276,Unnamed: 277,Unnamed: 278,Unnamed: 279,Unnamed: 280,Unnamed: 281,Unnamed: 282
0,NaT,361°kids,3E.life,4cm,ABLE JEANS,adidas originals,AFU,ALDOLA,ALL SELF,ANTA,...,云启荟肌,赵肥肠,中国电信,中国黄金,中国移动智能体验店,众客优品,周大福,周大生,筑巢鸟生活,卓诗尼
1,NaT,2068,3072,1B015,1B050B,1A055,3067B,2051,1A066,"1B003,1B005",...,B1008,4003,B1022,"B1032,B1033",3037B,3078,1A037,1A036,2055,2007
2,2018-12-01,1904,892,1408,621,1138,837,1264,1697,6566,...,530,1408,2752,1978,2264,726,1651,1966,1817,1427

In [8]:
name_store = list(traffic_store_day.iloc[0,1:])
name_store[:10]

['361°kids',
 '3E.life',
 '4cm',
 'ABLE JEANS',
 'adidas originals',
 'AFU',
 'ALDOLA',
 'ALL SELF',
 'ANTA',
 'ANTA KIDS']

In [9]:
id_store = list(traffic_store_day.iloc[1,1:])
id_store = [i.split(',') for i in id_store]
id_store[:10]

[['2068'],
 ['3072'],
 ['1B015'],
 ['1B050B'],
 ['1A055'],
 ['3067B'],
 ['2051'],
 ['1A066'],
 ['1B003', '1B005'],
 ['2069', '2070']]

<center>dict_store_name_id</center>

| key | value |
| :---- | :---- |
| 店铺名称 | 店面id |
| balabala | ['2063', '2065', '2066B']|

In [10]:
dict_store_name_id = dict(zip(name_store,id_store))
dict_store_name_id

{'361°kids': ['2068'],
 '3E.life': ['3072'],
 '4cm': ['1B015'],
 'ABLE JEANS': ['1B050B'],
 'adidas originals': ['1A055'],
 'AFU': ['3067B'],
 'ALDOLA': ['2051'],
 'ALL SELF': ['1A066'],
 'ANTA': ['1B003', '1B005'],
 'ANTA KIDS': ['2069', '2070'],
 'Apple': ['B1001'],
 'ARIOSE&YEARS': ['1A063'],
 'balabala': ['2063', '2065', '2066B'],
 'C+': ['4039'],
 'cabbeen': ['1B006'],
 'CAGO LIFE': ['3016', '3017', '3F-次主1B'],
 'Calvin Klein Jeans': ['1A039'],
 'Chic Passion': ['1B060B'],
 'CISSTEG': ['1B023B'],
 'CK PERFORMANCE': ['1A007'],
 'CK Underwear': ['1A052'],
 'coco都可': ['B1021'],
 'COSMO  LADY': ['2058'],
 'CRD': ['1A032'],
 'DBE': ['1A051'],
 'Diosa chocolate': ['2025'],
 'DUOZOULUMINI': ['1A016', '1A017A'],
 'ELLEBABY': ['2031'],
 'FILA': ['1A053'],
 'FILA FUSION': ['1A058'],
 'find钢琴智慧教室': ['3051A', '3051B'],
 'funlink+westlink集合店': ['1AF-次主2'],
 'FUN寿司': ['4015'],
 'GLORIA': ['1A061A', '1A061B', '1A061C'],
 'GUESS': ['1A005', '1A006'],
 'GXG': ['1B007'],
 'G大调': ['1A020'],
 'hely': ['1A068'],
 'HOZZS': ['1B056'],
 'I DO': ['1A069'],
 "imi's": ['1B023A'],
 'Inshop': ['1B069'],
 'INWARD': ['3077'],
 'IRA': ['1B009'],
 'J.LINDEBERG': ['1A002'],
 'Jack&Jones': ['1B019'],
 'JJLKIDS': ['2073'],
 'KAMA': ['1B025'],
 'KFC': ['B1038'],
 'KOI Thé': ['4021'],
 'LAXDN': ['1B010'],
 'LILY': ['1A025'],
 'LOVE&LOVE': ['1A033'],
 'MACMIOCO': ['2038'],
 'Mini Peace': ['2067'],
 'MJSTYLE': ['1BF-次主1'],
 'most': ['1B057'],
 'Nike Kicks Lounge': ['1A008', '1A009'],
 'NOME': ['B1005'],
 'Nr': ['1B061'],
 'OIT': ['1B013'],
 'Only': ['1B065', '1B066'],
 'Park dance': ['1A030'],
 'Peace bird(F)': ['1B062'],
 'PINK SHOP': ['1A029'],
 'PM潮汐': ['4001'],
 'POLO SPORT': ['1B059'],
 'POLO SPORT KIDS': ['2032'],
 'PQVISION': ['1B001'],
 'PRO.LIND': ['1A065'],
 'Raidy Boer': ['1A010'],
 'royaleat皇茶': ['3006'],
 'S.DEER': ['1B032'],
 'SANI撒尼': ['1A062'],
 'SELECTED': ['1B058'],
 'SEVEN CRASH': ['1A003'],
 'SHINE': ['1A067'],
 'SHOP1972': ['1B067'],
 'tatakids': ['2021'],
 'Tiyookid': ['2026'],
 'TO YOUNG': ['3001', '3002', '3003', '3005'],
 'TOMMY JEANS': ['1A050'],
 'UNIQLO': ['1AF-次主1'],
 'VeDA': ['1B050A'],
 'VERO MODA': ['1B028B', '1B029'],
 'vivo': ['3073', '3075'],
 'YRC': ['1B011'],
 '阿吉豆': ['1B068'],
 '阿香米线': ['4031'],
 '艾力斯特': ['3033'],
 '艾美家': ['2011'],
 '爱居兔': ['1B030'],
 '爱咪欧': ['4026'],
 '爱慕': ['1A023'],
 '爱西西': ['2071'],
 '安菲娅糖果铺': ['B1037'],
 '傲娇的小花椒': ['4035A'],
 '奥康': ['1B008'],
 '八方渔蛋': ['B1017'],
 '白禾': ['1B039C'],
 '半身缘': ['1B021'],
 '宝岛眼镜': ['1B039A'],
 '宝妈时光': ['2001'],
 '贝客新语': ['3012'],
 '贝优奇婴儿游泳馆': ['2035'],
 '犇牛记': ['4029'],
 '比音勒芬': ['1A056'],
 '必胜客': ['1B017', '1B018'],
 '波司登': ['1A017B'],
 '不二酸菜鱼': ['4030'],
 '城市宝宝': ['2018'],
 '仇婆抄手': ['B1016'],
 '厨人艺料·冷锅串串+火锅米线': ['B1019'],
 '大通冰室': ['3007'],
 '大玩家': ['2F-A'],
 '大鱼艺术': ['3008', '3009'],
 '弹个车': ['3080'],
 '德香苑': ['4017B'],
 '笛莎': ['2072'],
 '多喜爱': ['2008'],
 '朵拉格格': ['1B037'],
 '鄂尔多斯': ['1A057A'],
 '樊文花': ['B1029'],
 '梵妳卡波': ['2039'],
 '飞亚达': ['1A012'],
 '盖世红颜': ['3076'],
 '歌瑞尔': ['2012'],
 '古今书汉': ['3079'],
 '龟与熊猫': ['2013', '2015'],
 '桂牧庄': ['4037'],
 '海澜jeans': ['1B050A'],
 '海澜之家': ['1B055'],
 '海鲜大咖': ['4005', '4006B'],
 '韩悦': ['4050'],
 '汉邦剪裁': ['1A011'],
 '禾乐欧贝比': ['2016', '2017'],
 '禾雀': ['2066A'],
 '黑露珠宝': ['3069C'],
 '红豆男装': ['1B020'],
 '红馆': ['1A059'],
 '红孩子': ['2F-D'],
 '华伦天奴·奥兰迪': ['B1023'],
 '华硕': ['3032'],
 '华为': ['3037C', '3038', '3039'],
 '吉布鲁': ['4013'],
 '记约': ['1B031'],
 '江博士': ['2020A'],
 '匠道健身': ['4F-A'],
 '匠子烤鱼': ['4011'],
 '娇兰佳人': ['B1027'],
 '金妈家': ['4033'],
 '金苑': ['1B036'],
 '锦凤堂酸菜鸡': ['4016'],
 '劲霸': ['1B052'],
 '劲浪体育': ['1BF-A'],
 '景艺陶': ['3031'],
 '九东潮妆': ['B1028'],
 '九牧王': ['1B053'],
 '卡帝乐鳄鱼': ['1A057B'],
 '卡尔飞车': ['3063', '3065A', '3065B', '3066A', '3067A'],
 '卡茜米尔': ['1A028'],
 '康朴乐学习桌': ['2061'],
 '烤迎春日式烧肉': ['3015'],
 '刻为': ['1A026'],
 '酷乐潮玩': ['B1035'],
 '快乐柠檬': ['4006A'],
 '辣想啵啵鱼': ['4035B'],
 '莱得快': ['B1018'],
 '兰芳园1968': ['4008A'],
 '朗香': ['1B028A'],
 '雷诺眼镜': ['1B016'],
 '蕾特恩专业祛痘（国际）连锁': ['3059'],
 '棱镜密室逃脱': ['3052', '3053'],
 '立美力': ['2053B'],
 '脸谱造型': ['3062'],
 '良品铺子': ['B1003'],
 '靓影': ['3068', '3069A'],
 '廖记棒棒鸡': ['B1012A'],
 '林清轩': ['1A031'],
 '刘一手': ['4051'],
 '楼兰古玉': ['3069B'],
 '炉上粥香': ['4032'],
 '罗莱家纺': ['2057'],
 '珞臻珍珠': ['B1030'],
 '玛米玛卡': ['2030'],
 '满记甜品': ['1B026'],
 '曼斗泰傣主题餐厅': ['4008B', '4009'],
 '帽牌货冒菜': ['4019'],
 '美美袜铺': ['B1025'],
 '米洛西娅': ['2019'],
 '觅优生活': ['B1031'],
 '面包爱上茶': ['1A038'],
 '面包新语': ['B1036'],
 '名创优品': ['B1002'],
 '摩能肉蟹煲': ['4036'],
 '男生女生': ['2029'],
 '妮可美甲': ['B1007'],
 '妞妞仔仔儿童理发乐园': ['2075'],
 '牛男手造披萨': ['4012'],
 '纽约街头': ['3028B', '3028C', '3029A'],
 '帕帕珍味': ['B1012B', 'B1012C'],
 '樸術': ['1B012'],
 '七色纺': ['2009', '2010'],
 '柒叁村': ['3057'],
 '奇耙牛肉面': ['B1020'],
 '秋水伊人': ['1A060'],
 '屈臣氏': ['1A018', '1A019'],
 '趣动旅程儿童运动馆': ['2002', '2003'],
 '荣泰': ['3029B'],
 '荣耀手机': ['3078'],
 '蓉李记': ['4038'],
 '柔美': ['2059'],
 '瑞思英语': ['3030'],
 '润微': ['2050'],
 '塞飞洛': ['1B033'],
 '赛玛特': ['3035', '3036', '3037A'],
 '三福': ['2052', '2053A'],
 '三顾冒菜': ['B1013A', 'B1013B'],
 '色非': ['1B060A'],
 '森林鸟': ['1B063'],
 '山麒中古': ['3010'],
 '尚谷': ['B1010', 'B1011'],
 '尚品宅配': ['3070', '3071'],
 '拾麦': ['4027'],
 '视客.VR体验': ['3055', '3056A'],
 '首嘉产后恢复中心': ['3060'],
 '水云间': ['1A021', '1A022'],
 '四喜人': ['3066B'],
 '松上茶屋': ['3011'],
 '苏宁': ['3F-次主1A'],
 '素万乳胶寝具': ['2056'],
 '酸咪儿': ['2005'],
 '唐三彩': ['1B027'],
 '桃醉': ['4025'],
 '特步': ['1B039B'],
 '特步儿童': ['2062'],
 '铁锅门': ['4010'],
 '同仁古方养生': ['3061'],
 '万达宝贝王': ['2F-B'],
 '万达宝贝王早教中心': ['2F-C'],
 '万达影城': ['4F-B'],
 '唯美度': ['B1009'],
 '维纳贝拉': ['B1026'],
 '西町村屋': ['1B022'],
 '西豪果木牛排': ['4007'],
 '西树泡芙': ['4017A'],
 '鲜芋仙': ['3013'],
 '贤乐陶社': ['3058'],
 '橡皮筋': ['2020B', '2022', '2023', '2027', '2028'],
 '小巴扎的春天': ['4020'],
 '小涮哥': ['B1015'],
 '小圆圈亲子': ['2036', '2037'],
 '小猪班纳': ['2060'],
 '小资范': ['2033'],
 '谢瑞麟': ['1A035'],
 '新百伦领跑': ['2006'],
 '星巴克': ['1A001', '1B002'],
 '兄弟香辣蟹': ['4002'],
 '雅戈尔': ['1A013', '1A015'],
 '雅柔': ['1B035'],
 '雅斯澜美甲': ['3056B'],
 '言几又': ['3F-A'],
 '一把骨': ['4022', '4023'],
 '一起茶': ['4028'],
 '伊芙丽': ['1A027'],
 '亦芮': ['1B051'],
 '意尔康': ['1B038'],
 '永辉': ['B1-A'],
 '优棉莫待': ['B1006'],
 '悠茗堂': ['3007'],
 '又卷烧饼+海鲜遇上面': ['4018'],
 '云米全屋互联网家电': ['3050A', '3050B', '3050C'],
 '云启荟肌': ['B1008'],
 '赵肥肠': ['4003'],
 '中国电信': ['B1022'],
 '中国黄金': ['B1032', 'B1033'],
 '中国移动智能体验店': ['3037B'],
 '众客优品': ['3078'],
 '周大福': ['1A037'],
 '周大生': ['1A036'],
 '筑巢鸟生活': ['2055'],
 '卓诗尼': ['2007']}

In [11]:
dict_store_id_name={}
for name,ids in dict_store_name_id.items() :
    for id_ in ids:
        dict_store_id_name[id_]=name
dict_store_id_name

{'2068': '361°kids',
 '3072': '3E.life',
 '1B015': '4cm',
 '1B050B': 'ABLE JEANS',
 '1A055': 'adidas originals',
 '3067B': 'AFU',
 '2051': 'ALDOLA',
 '1A066': 'ALL SELF',
 '1B003': 'ANTA',
 '1B005': 'ANTA',
 '2069': 'ANTA KIDS',
 '2070': 'ANTA KIDS',
 'B1001': 'Apple',
 '1A063': 'ARIOSE&YEARS',
 '2063': 'balabala',
 '2065': 'balabala',
 '2066B': 'balabala',
 '4039': 'C+',
 '1B006': 'cabbeen',
 '3016': 'CAGO LIFE',
 '3017': 'CAGO LIFE',
 '3F-次主1B': 'CAGO LIFE',
 '1A039': 'Calvin Klein Jeans',
 '1B060B': 'Chic Passion',
 '1B023B': 'CISSTEG',
 '1A007': 'CK PERFORMANCE',
 '1A052': 'CK Underwear',
 'B1021': 'coco都可',
 '2058': 'COSMO  LADY',
 '1A032': 'CRD',
 '1A051': 'DBE',
 '2025': 'Diosa chocolate',
 '1A016': 'DUOZOULUMINI',
 '1A017A': 'DUOZOULUMINI',
 '2031': 'ELLEBABY',
 '1A053': 'FILA',
 '1A058': 'FILA FUSION',
 '3051A': 'find钢琴智慧教室',
 '3051B': 'find钢琴智慧教室',
 '1AF-次主2': 'funlink+westlink集合店',
 '4015': 'FUN寿司',
 '1A061A': 'GLORIA',
 '1A061B': 'GLORIA',
 '1A061C': 'GLORIA',
 '1A005': 'GUESS',
 '1A006': 'GUESS',
 '1B007': 'GXG',
 '1A020': 'G大调',
 '1A068': 'hely',
 '1B056': 'HOZZS',
 '1A069': 'I DO',
 '1B023A': "imi's",
 '1B069': 'Inshop',
 '3077': 'INWARD',
 '1B009': 'IRA',
 '1A002': 'J.LINDEBERG',
 '1B019': 'Jack&Jones',
 '2073': 'JJLKIDS',
 '1B025': 'KAMA',
 'B1038': 'KFC',
 '4021': 'KOI Thé',
 '1B010': 'LAXDN',
 '1A025': 'LILY',
 '1A033': 'LOVE&LOVE',
 '2038': 'MACMIOCO',
 '2067': 'Mini Peace',
 '1BF-次主1': 'MJSTYLE',
 '1B057': 'most',
 '1A008': 'Nike Kicks Lounge',
 '1A009': 'Nike Kicks Lounge',
 'B1005': 'NOME',
 '1B061': 'Nr',
 '1B013': 'OIT',
 '1B065': 'Only',
 '1B066': 'Only',
 '1A030': 'Park dance',
 '1B062': 'Peace bird(F)',
 '1A029': 'PINK SHOP',
 '4001': 'PM潮汐',
 '1B059': 'POLO SPORT',
 '2032': 'POLO SPORT KIDS',
 '1B001': 'PQVISION',
 '1A065': 'PRO.LIND',
 '1A010': 'Raidy Boer',
 '3006': 'royaleat皇茶',
 '1B032': 'S.DEER',
 '1A062': 'SANI撒尼',
 '1B058': 'SELECTED',
 '1A003': 'SEVEN CRASH',
 '1A067': 'SHINE',
 '1B067': 'SHOP1972',
 '2021': 'tatakids',
 '2026': 'Tiyookid',
 '3001': 'TO YOUNG',
 '3002': 'TO YOUNG',
 '3003': 'TO YOUNG',
 '3005': 'TO YOUNG',
 '1A050': 'TOMMY JEANS',
 '1AF-次主1': 'UNIQLO',
 '1B050A': '海澜jeans',
 '1B028B': 'VERO MODA',
 '1B029': 'VERO MODA',
 '3073': 'vivo',
 '3075': 'vivo',
 '1B011': 'YRC',
 '1B068': '阿吉豆',
 '4031': '阿香米线',
 '3033': '艾力斯特',
 '2011': '艾美家',
 '1B030': '爱居兔',
 '4026': '爱咪欧',
 '1A023': '爱慕',
 '2071': '爱西西',
 'B1037': '安菲娅糖果铺',
 '4035A': '傲娇的小花椒',
 '1B008': '奥康',
 'B1017': '八方渔蛋',
 '1B039C': '白禾',
 '1B021': '半身缘',
 '1B039A': '宝岛眼镜',
 '2001': '宝妈时光',
 '3012': '贝客新语',
 '2035': '贝优奇婴儿游泳馆',
 '4029': '犇牛记',
 '1A056': '比音勒芬',
 '1B017': '必胜客',
 '1B018': '必胜客',
 '1A017B': '波司登',
 '4030': '不二酸菜鱼',
 '2018': '城市宝宝',
 'B1016': '仇婆抄手',
 'B1019': '厨人艺料·冷锅串串+火锅米线',
 '3007': '悠茗堂',
 '2F-A': '大玩家',
 '3008': '大鱼艺术',
 '3009': '大鱼艺术',
 '3080': '弹个车',
 '4017B': '德香苑',
 '2072': '笛莎',
 '2008': '多喜爱',
 '1B037': '朵拉格格',
 '1A057A': '鄂尔多斯',
 'B1029': '樊文花',
 '2039': '梵妳卡波',
 '1A012': '飞亚达',
 '3076': '盖世红颜',
 '2012': '歌瑞尔',
 '3079': '古今书汉',
 '2013': '龟与熊猫',
 '2015': '龟与熊猫',
 '4037': '桂牧庄',
 '1B055': '海澜之家',
 '4005': '海鲜大咖',
 '4006B': '海鲜大咖',
 '4050': '韩悦',
 '1A011': '汉邦剪裁',
 '2016': '禾乐欧贝比',
 '2017': '禾乐欧贝比',
 '2066A': '禾雀',
 '3069C': '黑露珠宝',
 '1B020': '红豆男装',
 '1A059': '红馆',
 '2F-D': '红孩子',
 'B1023': '华伦天奴·奥兰迪',
 '3032': '华硕',
 '3037C': '华为',
 '3038': '华为',
 '3039': '华为',
 '4013': '吉布鲁',
 '1B031': '记约',
 '2020A': '江博士',
 '4F-A': '匠道健身',
 '4011': '匠子烤鱼',
 'B1027': '娇兰佳人',
 '4033': '金妈家',
 '1B036': '金苑',
 '4016': '锦凤堂酸菜鸡',
 '1B052': '劲霸',
 '1BF-A': '劲浪体育',
 '3031': '景艺陶',
 'B1028': '九东潮妆',
 '1B053': '九牧王',
 '1A057B': '卡帝乐鳄鱼',
 '3063': '卡尔飞车',
 '3065A': '卡尔飞车',
 '3065B': '卡尔飞车',
 '3066A': '卡尔飞车',
 '3067A': '卡尔飞车',
 '1A028': '卡茜米尔',
 '2061': '康朴乐学习桌',
 '3015': '烤迎春日式烧肉',
 '1A026': '刻为',
 'B1035': '酷乐潮玩',
 '4006A': '快乐柠檬',
 '4035B': '辣想啵啵鱼',
 'B1018': '莱得快',
 '4008A': '兰芳园1968',
 '1B028A': '朗香',
 '1B016': '雷诺眼镜',
 '3059': '蕾特恩专业祛痘（国际）连锁',
 '3052': '棱镜密室逃脱',
 '3053': '棱镜密室逃脱',
 '2053B': '立美力',
 '3062': '脸谱造型',
 'B1003': '良品铺子',
 '3068': '靓影',
 '3069A': '靓影',
 'B1012A': '廖记棒棒鸡',
 '1A031': '林清轩',
 '4051': '刘一手',
 '3069B': '楼兰古玉',
 '4032': '炉上粥香',
 '2057': '罗莱家纺',
 'B1030': '珞臻珍珠',
 '2030': '玛米玛卡',
 '1B026': '满记甜品',
 '4008B': '曼斗泰傣主题餐厅',
 '4009': '曼斗泰傣主题餐厅',
 '4019': '帽牌货冒菜',
 'B1025': '美美袜铺',
 '2019': '米洛西娅',
 'B1031': '觅优生活',
 '1A038': '面包爱上茶',
 'B1036': '面包新语',
 'B1002': '名创优品',
 '4036': '摩能肉蟹煲',
 '2029': '男生女生',
 'B1007': '妮可美甲',
 '2075': '妞妞仔仔儿童理发乐园',
 '4012': '牛男手造披萨',
 '3028B': '纽约街头',
 '3028C': '纽约街头',
 '3029A': '纽约街头',
 'B1012B': '帕帕珍味',
 'B1012C': '帕帕珍味',
 '1B012': '樸術',
 '2009': '七色纺',
 '2010': '七色纺',
 '3057': '柒叁村',
 'B1020': '奇耙牛肉面',
 '1A060': '秋水伊人',
 '1A018': '屈臣氏',
 '1A019': '屈臣氏',
 '2002': '趣动旅程儿童运动馆',
 '2003': '趣动旅程儿童运动馆',
 '3029B': '荣泰',
 '3078': '众客优品',
 '4038': '蓉李记',
 '2059': '柔美',
 '3030': '瑞思英语',
 '2050': '润微',
 '1B033': '塞飞洛',
 '3035': '赛玛特',
 '3036': '赛玛特',
 '3037A': '赛玛特',
 '2052': '三福',
 '2053A': '三福',
 'B1013A': '三顾冒菜',
 'B1013B': '三顾冒菜',
 '1B060A': '色非',
 '1B063': '森林鸟',
 '3010': '山麒中古',
 'B1010': '尚谷',
 'B1011': '尚谷',
 '3070': '尚品宅配',
 '3071': '尚品宅配',
 '4027': '拾麦',
 '3055': '视客.VR体验',
 '3056A': '视客.VR体验',
 '3060': '首嘉产后恢复中心',
 '1A021': '水云间',
 '1A022': '水云间',
 '3066B': '四喜人',
 '3011': '松上茶屋',
 '3F-次主1A': '苏宁',
 '2056': '素万乳胶寝具',
 '2005': '酸咪儿',
 '1B027': '唐三彩',
 '4025': '桃醉',
 '1B039B': '特步',
 '2062': '特步儿童',
 '4010': '铁锅门',
 '3061': '同仁古方养生',
 '2F-B': '万达宝贝王',
 '2F-C': '万达宝贝王早教中心',
 '4F-B': '万达影城',
 'B1009': '唯美度',
 'B1026': '维纳贝拉',
 '1B022': '西町村屋',
 '4007': '西豪果木牛排',
 '4017A': '西树泡芙',
 '3013': '鲜芋仙',
 '3058': '贤乐陶社',
 '2020B': '橡皮筋',
 '2022': '橡皮筋',
 '2023': '橡皮筋',
 '2027': '橡皮筋',
 '2028': '橡皮筋',
 '4020': '小巴扎的春天',
 'B1015': '小涮哥',
 '2036': '小圆圈亲子',
 '2037': '小圆圈亲子',
 '2060': '小猪班纳',
 '2033': '小资范',
 '1A035': '谢瑞麟',
 '2006': '新百伦领跑',
 '1A001': '星巴克',
 '1B002': '星巴克',
 '4002': '兄弟香辣蟹',
 '1A013': '雅戈尔',
 '1A015': '雅戈尔',
 '1B035': '雅柔',
 '3056B': '雅斯澜美甲',
 '3F-A': '言几又',
 '4022': '一把骨',
 '4023': '一把骨',
 '4028': '一起茶',
 '1A027': '伊芙丽',
 '1B051': '亦芮',
 '1B038': '意尔康',
 'B1-A': '永辉',
 'B1006': '优棉莫待',
 '4018': '又卷烧饼+海鲜遇上面',
 '3050A': '云米全屋互联网家电',
 '3050B': '云米全屋互联网家电',
 '3050C': '云米全屋互联网家电',
 'B1008': '云启荟肌',
 '4003': '赵肥肠',
 'B1022': '中国电信',
 'B1032': '中国黄金',
 'B1033': '中国黄金',
 '3037B': '中国移动智能体验店',
 '1A037': '周大福',
 '1A036': '周大生',
 '2055': '筑巢鸟生活',
 '2007': '卓诗尼'}

In [12]:
traffic_store_day = traffic_store_day[2:]
traffic_store_day['日期'] = pd.to_datetime(traffic_store_day['日期'])
traffic_store_day = traffic_store_day.set_index('日期',drop = True)
traffic_store_day.columns =[['店铺级' for i in name_store],name_store]
traffic_store_day.head()

                店铺级                                                        \
           361°kids 3E.life   4cm ABLE JEANS adidas originals  AFU ALDOLA
日期
2018-12-01     1904     892  1408        621             1138  837   1264
2018-12-02     1579     646  1506        521             1124  897   1109
2018-12-03      200     293   305        191              270  158    353
2018-12-04      167     217   414        199              210   68    256
2018-12-05      172     229   271        115              206  230    152

                                     ...                                    \
           ALL SELF  ANTA ANTA KIDS  ...  云启荟肌   赵肥肠  中国电信  中国黄金 中国移动智能体验店
日期                                   ...
2018-12-01     1697  6566      3663  ...   530  1408  2752  1978      2264
2018-12-02     1547  5182      2905  ...   394  1317  2455  1855      1890
2018-12-03      435   889       275  ...   322   519   633   402       591
2018-12-04      272   539       295  ...   358   650   473   311       560
2018-12-05      268   473       332  ...   401   433   444   393       437


           众客优品   周大福   周大生 筑巢鸟生活   卓诗尼
日期
2018-12-01  726  1651  1966  1817  1427
2018-12-02  435  1173  1281  2553  1260
2018-12-03  234   291   394   366   245
2018-12-04  146   228   389   196   255
2018-12-05  195   197   401   119   174

[5 rows x 282 columns]

### 停车入口日客流量

In [13]:
traffic_entry_parking_day= pd.read_excel(xlsx,'停车入口日客流量')
traffic_entry_parking_day.head(3)

          日期 停车场级 Unnamed: 2 Unnamed: 3 Unnamed: 4
0        NaT  混进口         入口       双入口右       双入口左
1        NaT  NaN        NaN        NaN        NaN
2 2018-12-01  NaN        NaN        NaN        NaN

In [14]:
name_entry_parking = list(traffic_entry_parking_day.iloc[0,1:])
name_entry_parking[:10]

['混进口', '入口', '双入口右', '双入口左']

In [15]:
traffic_entry_parking_day = traffic_entry_parking_day[2:]
traffic_entry_parking_day['日期'] = pd.to_datetime(traffic_entry_parking_day['日期'])
traffic_entry_parking_day = traffic_entry_parking_day.set_index('日期',drop = True)
traffic_entry_parking_day.columns = [['停车场级' for i in name_entry_parking],name_entry_parking]
traffic_entry_parking_day.tail()

           停车场级
            混进口    入口 双入口右 双入口左
日期
2019-03-27  150   610  200    4
2019-03-28  205   594  233    5
2019-03-29  208   621  294    9
2019-03-30  283  1110  533   38
2019-03-31  243   915  524   41

### 合并日客流量

In [16]:
traffic_day = pd.concat([traffic_pathway_day,traffic_store_day,traffic_entry_parking_day], axis=1)
traffic_day.head()

             广场级                                                          \
            10号门 1AF1/2/3号客梯厅旁通道 1AF-11号通道 1AF-1号消防电梯厅 1AF-2号通道 1AF-3号通道
日期
2018-12-01  5338             107      3029           0     5567        5
2018-12-02  3660             146      2442           6     5410       58
2018-12-03  1625              15       644           8     1917       12
2018-12-04  1507              16       506           1     1771       47
2018-12-05  1097              42       499           4     1717       16

                                                        ...        店铺级       \
           1AF-4号通道 1AF5号消防电梯厅 1AF6/7/8号客梯厅旁通道 1AF-6号通道 ...  中国移动智能体验店 众客优品
日期                                                      ...
2018-12-01     2384         41              65       42 ...       2264  726
2018-12-02     2100         30               9       50 ...       1890  435
2018-12-03      283         20               3        4 ...        591  234
2018-12-04      301         19               3       74 ...        560  146
2018-12-05      216          9               0       54 ...        437  195

                                   停车场级
             周大福   周大生 筑巢鸟生活   卓诗尼  混进口   入口 双入口右 双入口左
日期
2018-12-01  1651  1966  1817  1427  NaN  NaN  NaN  NaN
2018-12-02  1173  1281  2553  1260  NaN  NaN  NaN  NaN
2018-12-03   291   394   366   245  NaN  NaN  NaN  NaN
2018-12-04   228   389   196   255  NaN  NaN  NaN  NaN
2018-12-05   197   401   119   174  NaN  NaN  NaN  NaN

[5 rows x 352 columns]

In [17]:
[str(ts.date()) for ts in list(traffic_day.index)]

['2018-12-01',
 '2018-12-02',
 '2018-12-03',
 '2018-12-04',
 '2018-12-05',
 '2018-12-06',
 '2018-12-07',
 '2018-12-08',
 '2018-12-09',
 '2018-12-10',
 '2018-12-11',
 '2018-12-12',
 '2018-12-13',
 '2018-12-14',
 '2018-12-15',
 '2018-12-16',
 '2018-12-17',
 '2018-12-18',
 '2018-12-19',
 '2018-12-20',
 '2018-12-21',
 '2018-12-22',
 '2018-12-23',
 '2018-12-24',
 '2018-12-25',
 '2018-12-26',
 '2018-12-27',
 '2018-12-28',
 '2018-12-29',
 '2018-12-30',
 '2018-12-31',
 '2019-01-01',
 '2019-01-02',
 '2019-01-03',
 '2019-01-04',
 '2019-01-05',
 '2019-01-06',
 '2019-01-07',
 '2019-01-08',
 '2019-01-09',
 '2019-01-10',
 '2019-01-11',
 '2019-01-12',
 '2019-01-13',
 '2019-01-14',
 '2019-01-15',
 '2019-01-16',
 '2019-01-17',
 '2019-01-18',
 '2019-01-19',
 '2019-01-20',
 '2019-01-21',
 '2019-01-22',
 '2019-01-23',
 '2019-01-24',
 '2019-01-25',
 '2019-01-26',
 '2019-01-27',
 '2019-01-28',
 '2019-01-29',
 '2019-01-30',
 '2019-01-31',
 '2019-02-01',
 '2019-02-02',
 '2019-02-03',
 '2019-02-04',
 '2019-02-05',
 '2019-02-06',
 '2019-02-07',
 '2019-02-08',
 '2019-02-09',
 '2019-02-10',
 '2019-02-11',
 '2019-02-12',
 '2019-02-13',
 '2019-02-14',
 '2019-02-15',
 '2019-02-16',
 '2019-02-17',
 '2019-02-18',
 '2019-02-19',
 '2019-02-20',
 '2019-02-21',
 '2019-02-22',
 '2019-02-23',
 '2019-02-24',
 '2019-02-25',
 '2019-02-26',
 '2019-02-27',
 '2019-02-28',
 '2019-03-01',
 '2019-03-02',
 '2019-03-03',
 '2019-03-04',
 '2019-03-05',
 '2019-03-06',
 '2019-03-07',
 '2019-03-08',
 '2019-03-09',
 '2019-03-10',
 '2019-03-11',
 '2019-03-12',
 '2019-03-13',
 '2019-03-14',
 '2019-03-15',
 '2019-03-16',
 '2019-03-17',
 '2019-03-18',
 '2019-03-19',
 '2019-03-20',
 '2019-03-21',
 '2019-03-22',
 '2019-03-23',
 '2019-03-24',
 '2019-03-25',
 '2019-03-26',
 '2019-03-27',
 '2019-03-28',
 '2019-03-29',
 '2019-03-30',
 '2019-03-31']

In [18]:
traffic_day.isnull().sum(axis = 0)

广场级   10号门                0
      1AF1/2/3号客梯厅旁通道     0
      1AF-11号通道           0
      1AF-1号消防电梯厅         0
      1AF-2号通道            0
      1AF-3号通道            0
      1AF-4号通道            0
      1AF5号消防电梯厅          0
      1AF6/7/8号客梯厅旁通道     0
      1AF-6号通道            0
      1AF-7号通道            0
      1AF-8号通道            0
      1AF8号消防电梯厅          0
      1AF9号消防电梯厅          0
      1AF-B1/2扶梯通道        0
      1BF-5号消防电梯厅         0
      1BF-6号通道            0
      1BF-7号通道            0
      1BF-8号通道            0
      1BF北面室外广场至12号通道     0
      1BF夹层5号消防电梯厅        0
      1号门                 0
      2F5号消防电梯厅           0
      2F-6/7消防电梯厅         0
      2F北面室外广场至12号通道      0
      2号门                 0
      2号门旁通道              0
      3F4号消防电梯厅           0
      3号门                 0
      4F东面市政道路至广场通道       0
                         ..
店铺级   星巴克                 0
      兄弟香辣蟹               0
      雅戈尔                 0
      雅柔                  0
      雅斯澜美甲               0
      言几又                 0
      一把骨                 0
      一起茶                31
      伊芙丽                 0
      亦芮                  0
      意尔康                 0
      永辉                  0
      优棉莫待                0
      悠茗堂                90
      又卷烧饼+海鲜遇上面          0
      云米全屋互联网家电           0
      云启荟肌                0
      赵肥肠                31
      中国电信                0
      中国黄金                0
      中国移动智能体验店           0
      众客优品               31
      周大福                 0
      周大生                 0
      筑巢鸟生活               0
      卓诗尼                 0
停车场级  混进口                31
      入口                 31
      双入口右               31
      双入口左               31
Length: 352, dtype: int64

In [19]:
traffic_day.isnull().replace([1,0],[0,1])

            广场级                                                          \
           10号门 1AF1/2/3号客梯厅旁通道 1AF-11号通道 1AF-1号消防电梯厅 1AF-2号通道 1AF-3号通道
日期
2018-12-01    1               1         1           1        1        1
2018-12-02    1               1         1           1        1        1
2018-12-03    1               1         1           1        1        1
2018-12-04    1               1         1           1        1        1
2018-12-05    1               1         1           1        1        1
2018-12-06    1               1         1           1        1        1
2018-12-07    1               1         1           1        1        1
2018-12-08    1               1         1           1        1        1
2018-12-09    1               1         1           1        1        1
2018-12-10    1               1         1           1        1        1
2018-12-11    1               1         1           1        1        1
2018-12-12    1               1         1           1        1        1
2018-12-13    1               1         1           1        1        1
2018-12-14    1               1         1           1        1        1
2018-12-15    1               1         1           1        1        1
2018-12-16    1               1         1           1        1        1
2018-12-17    1               1         1           1        1        1
2018-12-18    1               1         1           1        1        1
2018-12-19    1               1         1           1        1        1
2018-12-20    1               1         1           1        1        1
2018-12-21    1               1         1           1        1        1
2018-12-22    1               1         1           1        1        1
2018-12-23    1               1         1           1        1        1
2018-12-24    1               1         1           1        1        1
2018-12-25    1               1         1           1        1        1
2018-12-26    1               1         1           1        1        1
2018-12-27    1               1         1           1        1        1
2018-12-28    1               1         1           1        1        1
2018-12-29    1               1         1           1        1        1
2018-12-30    1               1         1           1        1        1
...         ...             ...       ...         ...      ...      ...
2019-03-02    1               1         1           1        1        1
2019-03-03    1               1         1           1        1        1
2019-03-04    1               1         1           1        1        1
2019-03-05    1               1         1           1        1        1
2019-03-06    1               1         1           1        1        1
2019-03-07    1               1         1           1        1        1
2019-03-08    1               1         1           1        1        1
2019-03-09    1               1         1           1        1        1
2019-03-10    1               1         1           1        1        1
2019-03-11    1               1         1           1        1        1
2019-03-12    1               1         1           1        1        1
2019-03-13    1               1         1           1        1        1
2019-03-14    1               1         1           1        1        1
2019-03-15    1               1         1           1        1        1
2019-03-16    1               1         1           1        1        1
2019-03-17    1               1         1           1        1        1
2019-03-18    1               1         1           1        1        1
2019-03-19    1               1         1           1        1        1
2019-03-20    1               1         1           1        1        1
2019-03-21    1               1         1           1        1        1
2019-03-22    1               1         1           1        1        1
2019-03-23    1               1         1           1        1        1
2019-03-24    1               1         1           1        1        1
2019-03-25    1               1         1           1        1        1
2019-03-26    1               1         1           1        1        1
2019-03-27    1               1         1           1        1        1
2019-03-28    1               1         1           1        1        1
2019-03-29    1               1         1           1        1        1
2019-03-30    1               1         1           1        1        1
2019-03-31    1               1         1           1        1        1

                                                        ...        店铺级       \
           1AF-4号通道 1AF5号消防电梯厅 1AF6/7/8号客梯厅旁通道 1AF-6号通道 ...  中国移动智能体验店 众客优品
日期                                                      ...
2018-12-01        1          1               1        1 ...          1    1
2018-12-02        1          1               1        1 ...          1    1
2018-12-03        1          1               1        1 ...          1    1
2018-12-04        1          1               1        1 ...          1    1
2018-12-05        1          1               1        1 ...          1    1
2018-12-06        1          1               1        1 ...          1    1
2018-12-07        1          1               1        1 ...          1    1
2018-12-08        1          1               1        1 ...          1    1
2018-12-09        1          1               1        1 ...          1    1
2018-12-10        1          1               1        1 ...          1    1
2018-12-11        1          1               1        1 ...          1    1
2018-12-12        1          1               1        1 ...          1    1
2018-12-13        1          1               1        1 ...          1    1
2018-12-14        1          1               1        1 ...          1    1
2018-12-15        1          1               1        1 ...          1    1
2018-12-16        1          1               1        1 ...          1    1
2018-12-17        1          1               1        1 ...          1    1
2018-12-18        1          1               1        1 ...          1    1
2018-12-19        1          1               1        1 ...          1    1
2018-12-20        1          1               1        1 ...          1    1
2018-12-21        1          1               1        1 ...          1    1
2018-12-22        1          1               1        1 ...          1    1
2018-12-23        1          1               1        1 ...          1    1
2018-12-24        1          1               1        1 ...          1    1
2018-12-25        1          1               1        1 ...          1    1
2018-12-26        1          1               1        1 ...          1    1
2018-12-27        1          1               1        1 ...          1    1
2018-12-28        1          1               1        1 ...          1    1
2018-12-29        1          1               1        1 ...          1    1
2018-12-30        1          1               1        1 ...          1    1
...             ...        ...             ...      ... ...        ...  ...
2019-03-02        1          1               1        1 ...          1    1
2019-03-03        1          1               1        1 ...          1    1
2019-03-04        1          1               1        1 ...          1    1
2019-03-05        1          1               1        1 ...          1    1
2019-03-06        1          1               1        1 ...          1    1
2019-03-07        1          1               1        1 ...          1    1
2019-03-08        1          1               1        1 ...          1    1
2019-03-09        1          1               1        1 ...          1    1
2019-03-10        1          1               1        1 ...          1    1
2019-03-11        1          1               1        1 ...          1    1
2019-03-12        1          1               1        1 ...          1    1
2019-03-13        1          1               1        1 ...          1    1
2019-03-14        1          1               1        1 ...          1    1
2019-03-15        1          1               1        1 ...          1    1
2019-03-16        1          1               1        1 ...          1    1
2019-03-17        1          1               1        1 ...          1    1
2019-03-18        1          1               1        1 ...          1    1
2019-03-19        1          1               1        1 ...          1    1
2019-03-20        1          1               1        1 ...          1    1
2019-03-21        1          1               1        1 ...          1    1
2019-03-22        1          1               1        1 ...          1    1
2019-03-23        1          1               1        1 ...          1    1
2019-03-24        1          1               1        1 ...          1    1
2019-03-25        1          1               1        1 ...          1    1
2019-03-26        1          1               1        1 ...          1    1
2019-03-27        1          1               1        1 ...          1    1
2019-03-28        1          1               1        1 ...          1    1
2019-03-29        1          1               1        1 ...          1    1
2019-03-30        1          1               1        1 ...          1    1
2019-03-31        1          1               1        1 ...          1    1

                             停车场级
           周大福 周大生 筑巢鸟生活 卓诗尼  混进口 入口 双入口右 双入口左
日期
2018-12-01   1   1     1   1    1  1    1    1
2018-12-02   1   1     1   1    1  1    1    1
2018-12-03   1   1     1   1    1  1    1    1
2018-12-04   1   1     1   1    1  1    1    1
2018-12-05   1   1     1   1    1  1    1    1
2018-12-06   1   1     1   1    1  1    1    1
2018-12-07   1   1     1   1    1  1    1    1
2018-12-08   1   1     1   1    1  1    1    1
2018-12-09   1   1     1   1    1  1    1    1
2018-12-10   1   1     1   1    1  1    1    1
2018-12-11   1   1     1   1    1  1    1    1
2018-12-12   1   1     1   1    1  1    1    1
2018-12-13   1   1     1   1    1  1    1    1
2018-12-14   1   1     1   1    1  1    1    1
2018-12-15   1   1     1   1    1  1    1    1
2018-12-16   1   1     1   1    1  1    1    1
2018-12-17   1   1     1   1    1  1    1    1
2018-12-18   1   1     1   1    1  1    1    1
2018-12-19   1   1     1   1    1  1    1    1
2018-12-20   1   1     1   1    1  1    1    1
2018-12-21   1   1     1   1    1  1    1    1
2018-12-22   1   1     1   1    1  1    1    1
2018-12-23   1   1     1   1    1  1    1    1
2018-12-24   1   1     1   1    1  1    1    1
2018-12-25   1   1     1   1    1  1    1    1
2018-12-26   1   1     1   1    1  1    1    1
2018-12-27   1   1     1   1    1  1    1    1
2018-12-28   1   1     1   1    1  1    1    1
2018-12-29   1   1     1   1    1  1    1    1
2018-12-30   1   1     1   1    1  1    1    1
...         ..  ..   ...  ..  ... ..  ...  ...
2019-03-02   1   1     1   1    1  1    1    1
2019-03-03   1   1     1   1    1  1    1    1
2019-03-04   1   1     1   1    1  1    1    1
2019-03-05   1   1     1   1    1  1    1    1
2019-03-06   1   1     1   1    1  1    1    1
2019-03-07   1   1     1   1    1  1    1    1
2019-03-08   1   1     1   1    1  1    1    1
2019-03-09   1   1     1   1    1  1    1    1
2019-03-10   1   1     1   1    1  1    1    1
2019-03-11   1   1     1   1    1  1    1    1
2019-03-12   1   1     1   1    1  1    1    1
2019-03-13   1   1     1   1    1  1    1    1
2019-03-14   1   1     1   1    1  1    1    1
2019-03-15   1   1     1   1    1  1    1    1
2019-03-16   1   1     1   1    1  1    1    1
2019-03-17   1   1     1   1    1  1    1    1
2019-03-18   1   1     1   1    1  1    1    1
2019-03-19   1   1     1   1    1  1    1    1
2019-03-20   1   1     1   1    1  1    1    1
2019-03-21   1   1     1   1    1  1    1    1
2019-03-22   1   1     1   1    1  1    1    1
2019-03-23   1   1     1   1    1  1    1    1
2019-03-24   1   1     1   1    1  1    1    1
2019-03-25   1   1     1   1    1  1    1    1
2019-03-26   1   1     1   1    1  1    1    1
2019-03-27   1   1     1   1    1  1    1    1
2019-03-28   1   1     1   1    1  1    1    1
2019-03-29   1   1     1   1    1  1    1    1
2019-03-30   1   1     1   1    1  1    1    1
2019-03-31   1   1     1   1    1  1    1    1

[121 rows x 352 columns]

In [20]:
traffic_day.isnull().replace([True,False],[0,1]).prod(axis = 0)

广场级   10号门               1
      1AF1/2/3号客梯厅旁通道    1
      1AF-11号通道          1
      1AF-1号消防电梯厅        1
      1AF-2号通道           1
      1AF-3号通道           1
      1AF-4号通道           1
      1AF5号消防电梯厅         1
      1AF6/7/8号客梯厅旁通道    1
      1AF-6号通道           1
      1AF-7号通道           1
      1AF-8号通道           1
      1AF8号消防电梯厅         1
      1AF9号消防电梯厅         1
      1AF-B1/2扶梯通道       1
      1BF-5号消防电梯厅        1
      1BF-6号通道           1
      1BF-7号通道           1
      1BF-8号通道           1
      1BF北面室外广场至12号通道    1
      1BF夹层5号消防电梯厅       1
      1号门                1
      2F5号消防电梯厅          1
      2F-6/7消防电梯厅        1
      2F北面室外广场至12号通道     1
      2号门                1
      2号门旁通道             1
      3F4号消防电梯厅          1
      3号门                1
      4F东面市政道路至广场通道      1
                        ..
店铺级   星巴克                1
      兄弟香辣蟹              1
      雅戈尔                1
      雅柔                 1
      雅斯澜美甲              1
      言几又                1
      一把骨                1
      一起茶                1
      伊芙丽                1
      亦芮                 1
      意尔康                1
      永辉                 1
      优棉莫待               1
      悠茗堂                1
      又卷烧饼+海鲜遇上面         1
      云米全屋互联网家电          1
      云启荟肌               1
      赵肥肠                1
      中国电信               1
      中国黄金               1
      中国移动智能体验店          1
      众客优品               1
      周大福                1
      周大生                1
      筑巢鸟生活              1
      卓诗尼                1
停车场级  混进口                1
      入口                 1
      双入口右               1
      双入口左               1
Length: 352, dtype: int64

### 分时段客流数

In [21]:
traffic_hour= pd.read_excel(xlsx,'分时段客流数')
traffic_hour.head()

,日期,时段,广场级,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 323,Unnamed: 324,Unnamed: 325,Unnamed: 326,Unnamed: 327,Unnamed: 328,停车场级,Unnamed: 330,Unnamed: 331,Unnamed: 332
0,NaT,NaN,10号门,1AF1/2/3号客梯厅旁通道,1AF-11号通道,1AF-1号消防电梯厅,1AF-2号通道,1AF-3号通道,1AF-4号通道,1AF5号消防电梯厅,...,中国黄金,中国移动智能体验店,周大福,周大生,筑巢鸟生活,卓诗尼,混进口,入口,双入口右,双入口左
1,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"B1032,B1033",3037B,1A037,1A036,2055,2007,NaN,NaN,NaN,NaN
2,2019-03-01,10：00-11：00,37,2,18,0,19,2,1,0,...,17,15,8,15,12,2,6,28,11,0
3,NaT,11：00-12：00,60,3,8,0,29,0,1,0,...,11,19,3,12,4,7,5,40,14,0
4,NaT,12：00-13：00,80,1,8,0,19,0,9,0,...,15,24,2,12,4,7,12,30,15,0

In [22]:
temp = list(traffic_hour['日期'])[2:]
date =[]
for i in temp:
    if i == i: date.append(i)
    else: date.append(date[-1])

time = list(traffic_hour['时段'])[2:]

temp = list(traffic_hour.columns)[2:]
level =[]
for i in temp:
    if i[:7]=='Unnamed': level.append(level[-1])
    else: level.append(i)

name = list(traffic_hour.iloc[0,2:])
print(date[:10] , time[:10] , level[:10] , name[:10])

[Timestamp('2019-03-01 00:00:00'), Timestamp('2019-03-01 00:00:00'), Timestamp('2019-03-01 00:00:00'), Timestamp('2019-03-01 00:00:00'), Timestamp('2019-03-01 00:00:00'), Timestamp('2019-03-01 00:00:00'), Timestamp('2019-03-01 00:00:00'), Timestamp('2019-03-01 00:00:00'), Timestamp('2019-03-01 00:00:00'), Timestamp('2019-03-01 00:00:00')] ['10：00-11：00', '11：00-12：00', '12：00-13：00', '13：00-14：00', '14：00-15：00', '15：00-16：00', '16：00-17：00', '17：00-18：00', '18：00-19：00', '19：00-20：00'] ['广场级', '广场级', '广场级', '广场级', '广场级', '广场级', '广场级', '广场级', '广场级', '广场级'] ['10号门', '1AF1/2/3号客梯厅旁通道', '1AF-11号通道', '1AF-1号消防电梯厅', '1AF-2号通道', '1AF-3号通道', '1AF-4号通道', '1AF5号消防电梯厅', '1AF6/7/8号客梯厅旁通道', '1AF-6号通道']

In [23]:
traffic_hour = traffic_hour.iloc[2:,2:]
traffic_hour =traffic_hour.set_index([date,time])
traffic_hour.columns = [level,name]
traffic_hour

                        广场级                                                 \
                       10号门 1AF1/2/3号客梯厅旁通道 1AF-11号通道 1AF-1号消防电梯厅 1AF-2号通道
2019-03-01 10：00-11：00   37               2        18           0       19
           11：00-12：00   60               3         8           0       29
           12：00-13：00   80               1         8           0       19
           13：00-14：00   62               0        10           0       22
           14：00-15：00   75               1         8           0       29
           15：00-16：00   34               2         8           0       32
           16：00-17：00   69               2        18           0       19
           17：00-18：00   49               1        12           0       24
           18：00-19：00   52               0        16           0       14
           19：00-20：00   77               0         7           0       14
           20：00-21：00   30               0         5           0        5
           21：00-22：00   17               2         3           1       16
2019-03-02 10：00-11：00   47               1         8           0       26
           11：00-12：00   56               1        11           0       27
           12：00-13：00   57               1        10           0       27
           13：00-14：00   89               1        12           0       11
           14：00-15：00  118               0        15           1       29
           15：00-16：00   75               1        15           0       18
           16：00-17：00   70               3        30           0       14
           17：00-18：00   90               0         9           1       12
           18：00-19：00   80               0        20           0       14
           19：00-20：00   79               5         8           0        5
           20：00-21：00   33               7         7           1        5
           21：00-22：00   39               6         8           1        2
2019-03-03 10：00-11：00   55               2        13           1       18
           11：00-12：00   69               0         7           0       28
           12：00-13：00   99               0        20           0       12
           13：00-14：00   77               1        25           1       27
           14：00-15：00   99               4         9           0       45
           15：00-16：00  118               0        28           0       38
...                     ...             ...       ...         ...      ...
2019-03-29 16：00-17：00   41               2        28           0       11
           17：00-18：00   29               0        23           0       19
           18：00-19：00   51               1        19           0       19
           19：00-20：00   45               0        19           0       10
           20：00-21：00   24               0        24           0       17
           21：00-22：00   24               0         0           0        6
2019-03-30 10：00-11：00   34               0        23           0       35
           11：00-12：00   51               1        24           0       15
           12：00-13：00   48               1        37           0       27
           13：00-14：00   35               0        22           0       21
           14：00-15：00   63               1        12           0       28
           15：00-16：00   42               1        13           0       17
           16：00-17：00   73               0        14           0       25
           17：00-18：00   60               0        16           0       15
           18：00-19：00   48               5        22           0       12
           19：00-20：00   47               1        21           0        5
           20：00-21：00   23               1        13           0        9
           21：00-22：00   24               0         2           0       15
2019-03-31 10：00-11：00   35               0         7           0        8
           11：00-12：00   36               0        24           1       18
           12：00-13：00   46               4        20           0       10
           13：00-14：00   47               8        16           0       11
           14：00-15：00   56               2        17           0       16
           15：00-16：00   75               5        16           0       18
           16：00-17：00   85               0        31           0       22
           17：00-18：00   67               1        13           0       15
           18：00-19：00   59               1        22           0        6
           19：00-20：00   55               2        25           0       10
           20：00-21：00   28               0        14           0       12
           21：00-22：00    8               0         1           0        6

                                                                              \
                       1AF-3号通道 1AF-4号通道 1AF5号消防电梯厅 1AF6/7/8号客梯厅旁通道 1AF-6号通道
2019-03-01 10：00-11：00        2        1          0               0        0
           11：00-12：00        0        1          0               7        0
           12：00-13：00        0        9          0               6        0
           13：00-14：00        3        6          0              19        0
           14：00-15：00        0        4          2               9        0
           15：00-16：00        1        6          0              15        0
           16：00-17：00        0        4          0               7        0
           17：00-18：00        0        3          0               0        0
           18：00-19：00        0       11          0               4        0
           19：00-20：00        0       14          0               4        0
           20：00-21：00        0        8          0               5        0
           21：00-22：00        0       24          0               0        0
2019-03-02 10：00-11：00        0        6          0               3        0
           11：00-12：00        0        0          1               4        0
           12：00-13：00        0        6          0              14        0
           13：00-14：00        0        4          2               3        0
           14：00-15：00        1        3          0               4        0
           15：00-16：00        2        8          2               0        0
           16：00-17：00        0       10          0               4        0
           17：00-18：00        0       11          0               7        0
           18：00-19：00        3        8          2               5        0
           19：00-20：00        1        5          0              21        0
           20：00-21：00        0       20          1              12        0
           21：00-22：00        0       21          3               0        0
2019-03-03 10：00-11：00        0        3          4               1        0
           11：00-12：00        0        2          1               2        0
           12：00-13：00        0        4          0               1        0
           13：00-14：00        0       15          2               0        0
           14：00-15：00        0        9          6               1        2
           15：00-16：00        0       14          0               5        0
...                         ...      ...        ...             ...      ...
2019-03-29 16：00-17：00        0       16          0               3        0
           17：00-18：00        0        5          0               1        2
           18：00-19：00        0        4          2               2        0
           19：00-20：00        0       14          0               0        3
           20：00-21：00        0       30          2               4        0
           21：00-22：00        0       30          1               0        0
2019-03-30 10：00-11：00        0        7          0               0        0
           11：00-12：00        1       18          0               0        0
           12：00-13：00        0        9          0               1        0
           13：00-14：00        0       21          2               0        0
           14：00-15：00        1        7          0              17        2
           15：00-16：00        0       24          0               7        3
           16：00-17：00        1       31          2               8        0
           17：00-18：00        0       15          0               0        2
           18：00-19：00        2       23          0               2        0
           19：00-20：00        1       30          0               0        0
           20：00-21：00        0       33          0               0        0
           21：00-22：00        0       16          1               0        0
2019-03-31 10：00-11：00        1        9          0               0        0
           11：00-12：00        0       13          0               0        0
           12：00-13：00        0       12          2               0        0
           13：00-14：00        0        9          3               0        0
           14：00-15：00        0       10          1               2        2
           15：00-16：00        0       18          8               4        8
           16：00-17：00        0       25          4               2        6
           17：00-18：00        5       36          0               1        1
           18：00-19：00        0       18          2               2        0
           19：00-20：00        0        7          0               0        0
           20：00-21：00        0       23          1               2        0
           21：00-22：00        0       20          4               0        0

                       ...   店铺级                             停车场级            \
                       ...  中国黄金 中国移动智能体验店 周大福 周大生 筑巢鸟生活 卓诗尼  混进口   入口 双入口右
2019-03-01 10：00-11：00 ...    17        15   8  15    12   2    6   28   11
           11：00-12：00 ...    11        19   3  12     4   7    5   40   14
           12：00-13：00 ...    15        24   2  12     4   7   12   30   15
           13：00-14：00 ...    10        24   4  10     6   1    9   25   13
           14：00-15：00 ...    34        52   6  26    10   4    4   32   11
           15：00-16：00 ...    16        32   4  18    13   6    8   34   15
           16：00-17：00 ...    19        15   5  23     4  16    6   45   14
           17：00-18：00 ...    16        32   6  31    21   1    5   58   34
           18：00-19：00 ...     4        14   3   7     5   3    5   75   41
           19：00-20：00 ...    29        38   7  12     9  15    5   81   37
           20：00-21：00 ...    20        34  14   3    18   2   12   45   17
           21：00-22：00 ...    17        14   8  10    16   6    2   27    7
2019-03-02 10：00-11：00 ...    16        38  11  22    11   5    9   51   28
           11：00-12：00 ...    24        34   5  17     7   6    5   60   50
           12：00-13：00 ...    51        24   6  23     8   8   12   77   48
           13：00-14：00 ...     8        76   4  29     8   7    5   65   47
           14：00-15：00 ...    16        83   6  20    16  10    9   69   48
           15：00-16：00 ...    45        47   8  40    12  14   11   83   68
           16：00-17：00 ...    41        58  16  45    21   6    5   85   54
           17：00-18：00 ...    35        57  18  31    19   5    7   98   55
           18：00-19：00 ...    31        48   5  17     4   8   11  137   62
           19：00-20：00 ...    23        53   1   6    31   6   11  109   53
           20：00-21：00 ...    11        56   8   9    27   5    2   58   31
           21：00-22：00 ...    19        25   8   6    10   5    7   27    6
2019-03-03 10：00-11：00 ...    25        22   2  13     5  10    8   48   26
           11：00-12：00 ...    15        35   3  16    12   3    6   55   35
           12：00-13：00 ...     8        49   6  11    12   2   10   41   51
           13：00-14：00 ...    19        43   5  25    11   7    5   62   33
           14：00-15：00 ...    20        50  18  24    14  14    7   74   52
           15：00-16：00 ...    35        52   9  18    12  25   13   67   53
...                    ...   ...       ...  ..  ..   ...  ..  ...  ...  ...
2019-03-29 16：00-17：00 ...     8        11   7  14    12  11   11   51   28
           17：00-18：00 ...     8        12   9  10     4   4   17   47   28
           18：00-19：00 ...     9         8   4  17     3   5   16   60   41
           19：00-20：00 ...     6        21   5  14     8   2   11   77   32
           20：00-21：00 ...    16        18  11  12    10  20    5   49   22
           21：00-22：00 ...    16        20   9   6     5   6    9   28    5
2019-03-30 10：00-11：00 ...     8        13   9  30    17   6   26   70   76
           11：00-12：00 ...    18        31   9  30    13  19   21   84   55
           12：00-13：00 ...    14        27   4  34     9   7   30   94   54
           13：00-14：00 ...    15        41  14  26    18  17   27  105   38
           14：00-15：00 ...    15        18   4  41    12   2   29   98   49
           15：00-16：00 ...     7        19   6  32    19  18   13   88   42
           16：00-17：00 ...     9        32  40  10    18  14   11   78   35
           17：00-18：00 ...     9        30  14  22     3  16   10  107   40
           18：00-19：00 ...     5        28   5  27    12   3   24  102   44
           19：00-20：00 ...    15        43  14  22    14   7   20  110   41
           20：00-21：00 ...    33        25   8  15    18  11   13   49   15
           21：00-22：00 ...    17        27   5  12    19  15    2   24    8
2019-03-31 10：00-11：00 ...    18        15   0  20     7   6   11   87   36
           11：00-12：00 ...     7        24   3  10     7  22    9   76   61
           12：00-13：00 ...     7        25   1  18     3  13   25   71   42
           13：00-14：00 ...    23        22   4  23     9   6   19   69   53
           14：00-15：00 ...    18        41  15  25    11  14   18   78   43
           15：00-16：00 ...    44        46  16  24    17  33   17   90   62
           16：00-17：00 ...    10        41  38  43    12  39   27   88   56
           17：00-18：00 ...     6        24   9  35     6  17   19   64   50
           18：00-19：00 ...     8        14   8  12    11   9   24   91   53
           19：00-20：00 ...     9        19   6  16     4  11   13   66   26
           20：00-21：00 ...     6        16   6  21     9  17    6   27    4
           21：00-22：00 ...    16        16   3   6     4  11    7   16    1


                       双入口左
2019-03-01 10：00-11：00    0
           11：00-12：00    0
           12：00-13：00    0
           13：00-14：00    0
           14：00-15：00    0
           15：00-16：00    0
           16：00-17：00    0
           17：00-18：00    0
           18：00-19：00    3
           19：00-20：00    3
           20：00-21：00    2
           21：00-22：00    2
2019-03-02 10：00-11：00    1
           11：00-12：00    6
           12：00-13：00    1
           13：00-14：00    4
           14：00-15：00    4
           15：00-16：00    7
           16：00-17：00    2
           17：00-18：00    3
           18：00-19：00    6
           19：00-20：00    2
           20：00-21：00    1
           21：00-22：00    1
2019-03-03 10：00-11：00    0
           11：00-12：00    2
           12：00-13：00    0
           13：00-14：00    0
           14：00-15：00    5
           15：00-16：00    2
...                     ...
2019-03-29 16：00-17：00    1
           17：00-18：00    1
           18：00-19：00    3
           19：00-20：00    2
           20：00-21：00    0
           21：00-22：00    0
2019-03-30 10：00-11：00    3
           11：00-12：00    2
           12：00-13：00    3
           13：00-14：00    3
           14：00-15：00   11
           15：00-16：00    2
           16：00-17：00    2
           17：00-18：00    2
           18：00-19：00    8
           19：00-20：00    1
           20：00-21：00    0
           21：00-22：00    0
2019-03-31 10：00-11：00    0
           11：00-12：00    2
           12：00-13：00    2
           13：00-14：00    8
           14：00-15：00    0
           15：00-16：00    9
           16：00-17：00    9
           17：00-18：00    5
           18：00-19：00    1
           19：00-20：00    3
           20：00-21：00    0
           21：00-22：00    0

[372 rows x 331 columns]

### 计算指标

##### 日均车流

In [24]:
traffic_park_day = traffic_day['停车场级']
traffic_park_day.tail()

            混进口    入口 双入口右 双入口左
日期
2019-03-27  150   610  200    4
2019-03-28  205   594  233    5
2019-03-29  208   621  294    9
2019-03-30  283  1110  533   38
2019-03-31  243   915  524   41

In [25]:
traffic_park_day['weekday']=[True if i.weekday()<4 else False for i in traffic_park_day.index]
temp = traffic_park_day.fillna(0).groupby(['weekday']).mean().sum(axis=1)
temp[True]

C:\Users\LuoZN\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

573.75

In [26]:
traffic_park_day.sum(axis =1).mean()

745.6776859504132

In [27]:
with open('some.csv', 'w') as f:      # 采用b的方式处理可以省去很多问题
    writer = csv.writer(f)
    writer.writerow([1,2])
    #writer.writerow([traffic_park_day.sum(axis =1).mean(),2])

##### 平日日均车流

In [28]:
['日均车流',traffic_park_day.mean(axis = 0).sum()]

['日均车流', 1002.3286501377411]

In [29]:
traffic_park_day['weekday']=[True if i.weekday()<4 else False for i in traffic_park_day.index]
['平日日均车流',traffic_park_day.fillna(0).groupby(['weekday']).mean().sum(axis=1)[True]]

C:\Users\LuoZN\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

['平日日均车流', 573.75]

##### 周末日均车流

In [30]:
['周末日均车流',traffic_park_day.fillna(0).groupby(['weekday']).mean().sum(axis=1)[False]]

['周末日均车流', 964.9811320754717]

##### 停车入口x日均车流

In [31]:
del traffic_park_day['weekday']
a=traffic_park_day.mean()

In [32]:
a=traffic_park_day.mean()
[[x,i]for x,i in zip(a.index,a)]

[['混进口', 92.31111111111112],
 ['入口', 625.8444444444444],
 ['双入口右', 268.0777777777778],
 ['双入口左', 15.533333333333333]]

##### 主力店x日均

In [33]:
main_store =list(set([name for id_, name  in dict_store_id_name.items() if ('-' in id_)]))
main_store

['劲浪体育',
 '永辉',
 'CAGO LIFE',
 'UNIQLO',
 '万达宝贝王',
 '言几又',
 'MJSTYLE',
 '万达影城',
 '苏宁',
 '万达宝贝王早教中心',
 '大玩家',
 '红孩子',
 'funlink+westlink集合店',
 '匠道健身']

In [34]:
traffic_store_day = traffic_day['店铺级']
traffic_store_day.tail()

,361°kids,3E.life,4cm,ABLE JEANS,adidas originals,AFU,ALDOLA,ALL SELF,ANTA,ANTA KIDS,...,云启荟肌,赵肥肠,中国电信,中国黄金,中国移动智能体验店,众客优品,周大福,周大生,筑巢鸟生活,卓诗尼
日期,,,,,,,,,,,,,,,,,,,,,
2019-03-27,43,98,116,48,83,106,43,52,94,159,...,125,NaN,254,137,261,NaN,89,222,94,89
2019-03-28,137,83,101,116,110,86,48,38,135,201,...,214,NaN,312,149,282,NaN,87,246,117,98
2019-03-29,102,139,131,52,115,146,48,61,139,170,...,86,NaN,225,143,196,NaN,87,171,96,96
2019-03-30,192,239,149,75,153,170,73,44,273,356,...,138,NaN,288,212,357,NaN,144,315,183,145
2019-03-31,210,279,120,102,153,143,58,56,276,339,...,150,NaN,319,196,324,NaN,117,261,104,206

In [35]:
traffic_store_day.loc[:][main_store].mean()

劲浪体育                   1442.074380
永辉                     9803.123967
CAGO LIFE               484.173554
UNIQLO                 2097.264463
万达宝贝王                  2973.876033
言几又                     860.148760
MJSTYLE                 717.413223
万达影城                   3080.925620
苏宁                     1728.264463
万达宝贝王早教中心               641.157025
大玩家                    3847.628099
红孩子                    2138.181818
funlink+westlink集合店     572.520661
匠道健身                    780.950413
dtype: float64

##### 楼层日均

In [36]:
floor_store = [dict_store_name_id[name][0][:1] if dict_store_name_id[name][0][:2].isdigit() else dict_store_name_id[name][0][:2] for name in traffic_store_day.T.index]
floor_store

['2',
 '3',
 '1B',
 '1B',
 '1A',
 '3',
 '2',
 '1A',
 '1B',
 '2',
 'B1',
 '1A',
 '2',
 '4',
 '1B',
 '3',
 '1A',
 '1B',
 '1B',
 '1A',
 '1A',
 'B1',
 '2',
 '1A',
 '1A',
 '2',
 '1A',
 '2',
 '1A',
 '1A',
 '3',
 '1A',
 '4',
 '1A',
 '1A',
 '1B',
 '1A',
 '1A',
 '1B',
 '1A',
 '1B',
 '1B',
 '3',
 '1B',
 '1A',
 '1B',
 '2',
 '1B',
 'B1',
 '4',
 '1B',
 '1A',
 '1A',
 '2',
 '2',
 '1B',
 '1B',
 '1A',
 'B1',
 '1B',
 '1B',
 '1B',
 '1A',
 '1B',
 '1A',
 '4',
 '1B',
 '2',
 '1B',
 '1A',
 '1A',
 '3',
 '1B',
 '1A',
 '1B',
 '1A',
 '1A',
 '1B',
 '2',
 '2',
 '3',
 '1A',
 '1A',
 '1B',
 '1B',
 '3',
 '1B',
 '1B',
 '4',
 '3',
 '2',
 '1B',
 '4',
 '1A',
 '2',
 'B1',
 '4',
 '1B',
 'B1',
 '1B',
 '1B',
 '1B',
 '2',
 '3',
 '2',
 '4',
 '1A',
 '1B',
 '1A',
 '4',
 '2',
 'B1',
 'B1',
 '3',
 '2F',
 '3',
 '3',
 '4',
 '2',
 '2',
 '1B',
 '1A',
 'B1',
 '2',
 '1A',
 '3',
 '2',
 '3',
 '2',
 '4',
 '1B',
 '1B',
 '4',
 '4',
 '1A',
 '2',
 '2',
 '3',
 '1B',
 '1A',
 '2F',
 'B1',
 '3',
 '3',
 '4',
 '1B',
 '2',
 '4F',
 '4',
 'B1',
 '4',
 '1B',
 '4',
 '1B',
 '1B',
 '3',
 'B1',
 '1B',
 '1A',
 '3',
 '1A',
 '2',
 '3',
 '1A',
 'B1',
 '4',
 '4',
 'B1',
 '4',
 '1B',
 '1B',
 '3',
 '3',
 '2',
 '3',
 'B1',
 '3',
 'B1',
 '1A',
 '4',
 '3',
 '4',
 '2',
 'B1',
 '2',
 '1B',
 '4',
 '4',
 'B1',
 '2',
 'B1',
 '1A',
 'B1',
 'B1',
 '4',
 '2',
 'B1',
 '2',
 '4',
 '3',
 'B1',
 '1B',
 '2',
 '3',
 'B1',
 '1A',
 '1A',
 '2',
 '3',
 '3',
 '4',
 '2',
 '3',
 '2',
 '1B',
 '3',
 '2',
 'B1',
 '1B',
 '1B',
 '3',
 'B1',
 '3',
 '4',
 '3',
 '3',
 '1A',
 '3',
 '3',
 '3F',
 '2',
 '2',
 '1B',
 '4',
 '1B',
 '2',
 '4',
 '3',
 '2F',
 '2F',
 '4F',
 'B1',
 'B1',
 '1B',
 '4',
 '4',
 '3',
 '3',
 '2',
 '4',
 'B1',
 '2',
 '2',
 '2',
 '1A',
 '2',
 '1A',
 '4',
 '1A',
 '1B',
 '3',
 '3F',
 '4',
 '4',
 '1A',
 '1B',
 '1B',
 'B1',
 'B1',
 '3',
 '4',
 '3',
 'B1',
 '4',
 'B1',
 'B1',
 '3',
 '3',
 '1A',
 '1A',
 '2',
 '2']

In [37]:
traffic_floor_day = traffic_store_day.T
traffic_floor_day['floor'] = floor_store
temp1 = traffic_floor_day.groupby(['floor']).sum().mean(axis = 1)
temp1

floor
1A    13793.289256
1B    18820.280992
2     17413.983471
2F     9600.842975
3     11324.107438
3F     2588.413223
4     16194.768595
4F     3861.876033
B1    24250.413223
dtype: float64

In [38]:
temp2 = traffic_floor_day.loc[main_store][:].groupby(['floor']).sum().mean(axis = 1)
temp2

floor
1A    2669.785124
1B    2159.487603
2F    9600.842975
3      484.173554
3F    2588.413223
4F    3861.876033
B1    9803.123967
dtype: float64

In [39]:
print(temp2.div(temp1))

floor
1A    0.193557
1B    0.114743
2          NaN
2F    1.000000
3     0.042756
3F    1.000000
4          NaN
4F    1.000000
B1    0.404246
dtype: float64

In [40]:
len(temp2.div(temp1))

9

In [47]:
def get_num_null(traffic):
        num_null = traffic.isnull().sum(axis = 0)
        return num_null

In [48]:
num_null_day = get_num_null(traffic_day)

In [51]:
num_null_day[0]

0

In [54]:
list(num_null_day.index)

[('广场级', '10号门'),
 ('广场级', '1AF1/2/3号客梯厅旁通道'),
 ('广场级', '1AF-11号通道'),
 ('广场级', '1AF-1号消防电梯厅'),
 ('广场级', '1AF-2号通道'),
 ('广场级', '1AF-3号通道'),
 ('广场级', '1AF-4号通道'),
 ('广场级', '1AF5号消防电梯厅'),
 ('广场级', '1AF6/7/8号客梯厅旁通道'),
 ('广场级', '1AF-6号通道'),
 ('广场级', '1AF-7号通道'),
 ('广场级', '1AF-8号通道'),
 ('广场级', '1AF8号消防电梯厅'),
 ('广场级', '1AF9号消防电梯厅'),
 ('广场级', '1AF-B1/2扶梯通道'),
 ('广场级', '1BF-5号消防电梯厅'),
 ('广场级', '1BF-6号通道'),
 ('广场级', '1BF-7号通道'),
 ('广场级', '1BF-8号通道'),
 ('广场级', '1BF北面室外广场至12号通道'),
 ('广场级', '1BF夹层5号消防电梯厅'),
 ('广场级', '1号门'),
 ('广场级', '2F5号消防电梯厅'),
 ('广场级', '2F-6/7消防电梯厅'),
 ('广场级', '2F北面室外广场至12号通道'),
 ('广场级', '2号门'),
 ('广场级', '2号门旁通道'),
 ('广场级', '3F4号消防电梯厅'),
 ('广场级', '3号门'),
 ('广场级', '4F东面市政道路至广场通道'),
 ('广场级', '4号门（CAGO LIFE外围通道）'),
 ('广场级', '5F农场通道'),
 ('广场级', '5号门'),
 ('广场级', '7号门'),
 ('广场级', '8号门'),
 ('广场级', '9号门'),
 ('广场级', 'B1F1/2/3号客梯厅'),
 ('广场级', 'B1F4/5号客梯厅'),
 ('广场级', 'B1F5号消防电梯厅'),
 ('广场级', 'B1F6/7号消防电梯梯厅'),
 ('广场级', 'B1F-8号通道(超市停车场通道）)'),
 ('广场级', 'B2-1/B2-2扶梯厅'),
 ('广场级', 'B2-3/B2-4扶梯厅'),
 ('广场级', 'B2F1/2/3号客梯厅'),
 ('广场级', 'B2F10/11号消防电梯厅'),
 ('广场级', 'B2F2/3号消防电梯厅'),
 ('广场级', 'B2F4/5号客梯厅'),
 ('广场级', 'B2F6/7/8号客梯厅'),
 ('广场级', 'B2F6/7号消防电梯梯厅'),
 ('广场级', 'B2F8号消防电梯厅'),
 ('广场级', 'B2F9号消防电梯厅'),
 ('广场级', 'FUNLINK&WESTLINK外围通道'),
 ('广场级', 'J.LINDEBERG外围通道'),
 ('广场级', 'KFC外围通道'),
 ('广场级', 'Nike Kicks Lounge外围通道'),
 ('广场级', 'Park Dance外围通道'),
 ('广场级', 'UNIQLO外围通道'),
 ('广场级', 'VERO MODA外围通道'),
 ('广场级', '宝贝王外围通道'),
 ('广场级', '宝贝王早教外围通道'),
 ('广场级', '大玩家外围通道'),
 ('广场级', '汉邦剪裁外围通道'),
 ('广场级', '苏宁外围通道'),
 ('广场级', '西面1AF至1BF楼梯通道'),
 ('广场级', '橡皮筋外围通道'),
 ('广场级', '星巴克外围通道'),
 ('店铺级', '361°kids'),
 ('店铺级', '3E.life'),
 ('店铺级', '4cm'),
 ('店铺级', 'ABLE JEANS'),
 ('店铺级', 'adidas originals'),
 ('店铺级', 'AFU'),
 ('店铺级', 'ALDOLA'),
 ('店铺级', 'ALL SELF'),
 ('店铺级', 'ANTA'),
 ('店铺级', 'ANTA KIDS'),
 ('店铺级', 'Apple'),
 ('店铺级', 'ARIOSE&YEARS'),
 ('店铺级', 'balabala'),
 ('店铺级', 'C+'),
 ('店铺级', 'cabbeen'),
 ('店铺级', 'CAGO LIFE'),
 ('店铺级', 'Calvin Klein Jeans'),
 ('店铺级', 'Chic Passion'),
 ('店铺级', 'CISSTEG'),
 ('店铺级', 'CK PERFORMANCE'),
 ('店铺级', 'CK Underwear'),
 ('店铺级', 'coco都可'),
 ('店铺级', 'COSMO  LADY'),
 ('店铺级', 'CRD'),
 ('店铺级', 'DBE'),
 ('店铺级', 'Diosa chocolate'),
 ('店铺级', 'DUOZOULUMINI'),
 ('店铺级', 'ELLEBABY'),
 ('店铺级', 'FILA'),
 ('店铺级', 'FILA FUSION'),
 ('店铺级', 'find钢琴智慧教室'),
 ('店铺级', 'funlink+westlink集合店'),
 ('店铺级', 'FUN寿司'),
 ('店铺级', 'GLORIA'),
 ('店铺级', 'GUESS'),
 ('店铺级', 'GXG'),
 ('店铺级', 'G大调'),
 ('店铺级', 'hely'),
 ('店铺级', 'HOZZS'),
 ('店铺级', 'I DO'),
 ('店铺级', "imi's"),
 ('店铺级', 'Inshop'),
 ('店铺级', 'INWARD'),
 ('店铺级', 'IRA'),
 ('店铺级', 'J.LINDEBERG'),
 ('店铺级', 'Jack&Jones'),
 ('店铺级', 'JJLKIDS'),
 ('店铺级', 'KAMA'),
 ('店铺级', 'KFC'),
 ('店铺级', 'KOI Thé'),
 ('店铺级', 'LAXDN'),
 ('店铺级', 'LILY'),
 ('店铺级', 'LOVE&LOVE'),
 ('店铺级', 'MACMIOCO'),
 ('店铺级', 'Mini Peace'),
 ('店铺级', 'MJSTYLE'),
 ('店铺级', 'most'),
 ('店铺级', 'Nike Kicks Lounge'),
 ('店铺级', 'NOME'),
 ('店铺级', 'Nr'),
 ('店铺级', 'OIT'),
 ('店铺级', 'Only'),
 ('店铺级', 'Park dance'),
 ('店铺级', 'Peace bird(F)'),
 ('店铺级', 'PINK SHOP'),
 ('店铺级', 'PM潮汐'),
 ('店铺级', 'POLO SPORT'),
 ('店铺级', 'POLO SPORT KIDS'),
 ('店铺级', 'PQVISION'),
 ('店铺级', 'PRO.LIND'),
 ('店铺级', 'Raidy Boer'),
 ('店铺级', 'royaleat皇茶'),
 ('店铺级', 'S.DEER'),
 ('店铺级', 'SANI撒尼'),
 ('店铺级', 'SELECTED'),
 ('店铺级', 'SEVEN CRASH'),
 ('店铺级', 'SHINE'),
 ('店铺级', 'SHOP1972'),
 ('店铺级', 'tatakids'),
 ('店铺级', 'Tiyookid'),
 ('店铺级', 'TO YOUNG'),
 ('店铺级', 'TOMMY JEANS'),
 ('店铺级', 'UNIQLO'),
 ('店铺级', 'VeDA'),
 ('店铺级', 'VERO MODA'),
 ('店铺级', 'vivo'),
 ('店铺级', 'YRC'),
 ('店铺级', '阿吉豆'),
 ('店铺级', '阿香米线'),
 ('店铺级', '艾力斯特'),
 ('店铺级', '艾美家'),
 ('店铺级', '爱居兔'),
 ('店铺级', '爱咪欧'),
 ('店铺级', '爱慕'),
 ('店铺级', '爱西西'),
 ('店铺级', '安菲娅糖果铺'),
 ('店铺级', '傲娇的小花椒'),
 ('店铺级', '奥康'),
 ('店铺级', '八方渔蛋'),
 ('店铺级', '白禾'),
 ('店铺级', '半身缘'),
 ('店铺级', '宝岛眼镜'),
 ('店铺级', '宝妈时光'),
 ('店铺级', '贝客新语'),
 ('店铺级', '贝优奇婴儿游泳馆'),
 ('店铺级', '犇牛记'),
 ('店铺级', '比音勒芬'),
 ('店铺级', '必胜客'),
 ('店铺级', '波司登'),
 ('店铺级', '不二酸菜鱼'),
 ('店铺级', '城市宝宝'),
 ('店铺级', '仇婆抄手'),
 ('店铺级', '厨人艺料·冷锅串串+火锅米线'),
 ('店铺级', '大通冰室'),
 ('店铺级', '大玩家'),
 ('店铺级', '大鱼艺术'),
 ('店铺级', '弹个车'),
 ('店铺级', '德香苑'),
 ('店铺级', '笛莎'),
 ('店铺级', '多喜爱'),
 ('店铺级', '朵拉格格'),
 ('店铺级', '鄂尔多斯'),
 ('店铺级', '樊文花'),
 ('店铺级', '梵妳卡波'),
 ('店铺级', '飞亚达'),
 ('店铺级', '盖世红颜'),
 ('店铺级', '歌瑞尔'),
 ('店铺级', '古今书汉'),
 ('店铺级', '龟与熊猫'),
 ('店铺级', '桂牧庄'),
 ('店铺级', '海澜jeans'),
 ('店铺级', '海澜之家'),
 ('店铺级', '海鲜大咖'),
 ('店铺级', '韩悦'),
 ('店铺级', '汉邦剪裁'),
 ('店铺级', '禾乐欧贝比'),
 ('店铺级', '禾雀'),
 ('店铺级', '黑露珠宝'),
 ('店铺级', '红豆男装'),
 ('店铺级', '红馆'),
 ('店铺级', '红孩子'),
 ('店铺级', '华伦天奴·奥兰迪'),
 ('店铺级', '华硕'),
 ('店铺级', '华为'),
 ('店铺级', '吉布鲁'),
 ('店铺级', '记约'),
 ('店铺级', '江博士'),
 ('店铺级', '匠道健身'),
 ('店铺级', '匠子烤鱼'),
 ('店铺级', '娇兰佳人'),
 ('店铺级', '金妈家'),
 ('店铺级', '金苑'),
 ('店铺级', '锦凤堂酸菜鸡'),
 ('店铺级', '劲霸'),
 ('店铺级', '劲浪体育'),
 ('店铺级', '景艺陶'),
 ('店铺级', '九东潮妆'),
 ('店铺级', '九牧王'),
 ('店铺级', '卡帝乐鳄鱼'),
 ('店铺级', '卡尔飞车'),
 ('店铺级', '卡茜米尔'),
 ('店铺级', '康朴乐学习桌'),
 ('店铺级', '烤迎春日式烧肉'),
 ('店铺级', '刻为'),
 ('店铺级', '酷乐潮玩'),
 ('店铺级', '快乐柠檬'),
 ('店铺级', '辣想啵啵鱼'),
 ('店铺级', '莱得快'),
 ('店铺级', '兰芳园1968'),
 ('店铺级', '朗香'),
 ('店铺级', '雷诺眼镜'),
 ('店铺级', '蕾特恩专业祛痘（国际）连锁'),
 ('店铺级', '棱镜密室逃脱'),
 ('店铺级', '立美力'),
 ('店铺级', '脸谱造型'),
 ('店铺级', '良品铺子'),
 ('店铺级', '靓影'),
 ('店铺级', '廖记棒棒鸡'),
 ('店铺级', '林清轩'),
 ('店铺级', '刘一手'),
 ('店铺级', '楼兰古玉'),
 ('店铺级', '炉上粥香'),
 ('店铺级', '罗莱家纺'),
 ('店铺级', '珞臻珍珠'),
 ('店铺级', '玛米玛卡'),
 ('店铺级', '满记甜品'),
 ('店铺级', '曼斗泰傣主题餐厅'),
 ('店铺级', '帽牌货冒菜'),
 ('店铺级', '美美袜铺'),
 ('店铺级', '米洛西娅'),
 ('店铺级', '觅优生活'),
 ('店铺级', '面包爱上茶'),
 ('店铺级', '面包新语'),
 ('店铺级', '名创优品'),
 ('店铺级', '摩能肉蟹煲'),
 ('店铺级', '男生女生'),
 ('店铺级', '妮可美甲'),
 ('店铺级', '妞妞仔仔儿童理发乐园'),
 ('店铺级', '牛男手造披萨'),
 ('店铺级', '纽约街头'),
 ('店铺级', '帕帕珍味'),
 ('店铺级', '樸術'),
 ('店铺级', '七色纺'),
 ('店铺级', '柒叁村'),
 ('店铺级', '奇耙牛肉面'),
 ('店铺级', '秋水伊人'),
 ('店铺级', '屈臣氏'),
 ('店铺级', '趣动旅程儿童运动馆'),
 ('店铺级', '荣泰'),
 ('店铺级', '荣耀手机'),
 ('店铺级', '蓉李记'),
 ('店铺级', '柔美'),
 ('店铺级', '瑞思英语'),
 ('店铺级', '润微'),
 ('店铺级', '塞飞洛'),
 ('店铺级', '赛玛特'),
 ('店铺级', '三福'),
 ('店铺级', '三顾冒菜'),
 ('店铺级', '色非'),
 ('店铺级', '森林鸟'),
 ('店铺级', '山麒中古'),
 ('店铺级', '尚谷'),
 ('店铺级', '尚品宅配'),
 ('店铺级', '拾麦'),
 ('店铺级', '视客.VR体验'),
 ('店铺级', '首嘉产后恢复中心'),
 ('店铺级', '水云间'),
 ('店铺级', '四喜人'),
 ('店铺级', '松上茶屋'),
 ('店铺级', '苏宁'),
 ('店铺级', '素万乳胶寝具'),
 ('店铺级', '酸咪儿'),
 ('店铺级', '唐三彩'),
 ('店铺级', '桃醉'),
 ('店铺级', '特步'),
 ('店铺级', '特步儿童'),
 ('店铺级', '铁锅门'),
 ('店铺级', '同仁古方养生'),
 ('店铺级', '万达宝贝王'),
 ('店铺级', '万达宝贝王早教中心'),
 ('店铺级', '万达影城'),
 ('店铺级', '唯美度'),
 ('店铺级', '维纳贝拉'),
 ('店铺级', '西町村屋'),
 ('店铺级', '西豪果木牛排'),
 ('店铺级', '西树泡芙'),
 ('店铺级', '鲜芋仙'),
 ('店铺级', '贤乐陶社'),
 ('店铺级', '橡皮筋'),
 ('店铺级', '小巴扎的春天'),
 ('店铺级', '小涮哥'),
 ('店铺级', '小圆圈亲子'),
 ('店铺级', '小猪班纳'),
 ('店铺级', '小资范'),
 ('店铺级', '谢瑞麟'),
 ('店铺级', '新百伦领跑'),
 ('店铺级', '星巴克'),
 ('店铺级', '兄弟香辣蟹'),
 ('店铺级', '雅戈尔'),
 ('店铺级', '雅柔'),
 ('店铺级', '雅斯澜美甲'),
 ('店铺级', '言几又'),
 ('店铺级', '一把骨'),
 ('店铺级', '一起茶'),
 ('店铺级', '伊芙丽'),
 ('店铺级', '亦芮'),
 ('店铺级', '意尔康'),
 ('店铺级', '永辉'),
 ('店铺级', '优棉莫待'),
 ('店铺级', '悠茗堂'),
 ('店铺级', '又卷烧饼+海鲜遇上面'),
 ('店铺级', '云米全屋互联网家电'),
 ('店铺级', '云启荟肌'),
 ('店铺级', '赵肥肠'),
 ('店铺级', '中国电信'),
 ('店铺级', '中国黄金'),
 ('店铺级', '中国移动智能体验店'),
 ('店铺级', '众客优品'),
 ('店铺级', '周大福'),
 ('店铺级', '周大生'),
 ('店铺级', '筑巢鸟生活'),
 ('店铺级', '卓诗尼'),
 ('停车场级', '混进口'),
 ('停车场级', '入口'),
 ('停车场级', '双入口右'),
 ('停车场级', '双入口左')]